In [2]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [6]:
import tensorflow as tf
print(tf.__version__)
from tensorflow.keras.preprocessing.text import one_hot

2.19.0


In [7]:
voc_size = 500

In [9]:
onehot_repr = [one_hot(word,voc_size)for word in sent]
print(onehot_repr)

[[52, 378, 403, 498, 31, 122], [339, 210, 403, 456, 327, 98], [452, 235, 472, 393], [52, 357, 403, 199, 52, 26], [419, 204, 143, 403, 456, 327, 98], [257, 403, 456, 327, 478, 335]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [13]:
sent_length = 8
emb_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(emb_docs)

[[  0   0  52 378 403 498  31 122]
 [  0   0 339 210 403 456 327  98]
 [  0   0   0   0 452 235 472 393]
 [  0   0  52 357 403 199  52  26]
 [  0 419 204 143 403 456 327  98]
 [  0   0 257 403 456 327 478 335]]


In [14]:
dim = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size,dim))
model.compile(optimizer = 'adam',loss = 'mse')
model.build(input_shape=(None,sent_length))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
emb_docs[0]

array([  0,   0,  52, 378, 403, 498,  31, 122], dtype=int32)

In [20]:
model.predict(np.expand_dims(emb_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[[-0.00698385,  0.03513254,  0.03457221, -0.02674037,
          0.03307373,  0.00498961, -0.00561097,  0.03693732,
         -0.02244395,  0.04898347],
        [-0.00698385,  0.03513254,  0.03457221, -0.02674037,
          0.03307373,  0.00498961, -0.00561097,  0.03693732,
         -0.02244395,  0.04898347],
        [-0.04096595,  0.04298177,  0.03873919,  0.02906017,
         -0.00309141,  0.03654299,  0.00260581,  0.00066593,
          0.00921663,  0.04872013],
        [-0.04358676, -0.00242213,  0.04673694,  0.0402154 ,
         -0.01338872, -0.038383  ,  0.01030393, -0.00589694,
          0.04183558,  0.00629963],
        [-0.03683035, -0.02030442,  0.0269871 , -0.00465488,
          0.03367137, -0.0318053 , -0.04354003, -0.01492433,
          0.0066003 , -0.02505594],
        [-0.0079307 ,  0.03917344,  0.01571733, -0.03728328,
         -0.01485976, -0.04320704,  0.02932736,  0.01688099,
          0.0270484 ,  0.03606853],
        [ 0.02711574, -0.01396067, -0.01248847,  0.0