In [89]:
import numpy as np
import torch

In [90]:
#making training data
#input variables ---> (temp,rainfall,humidity)---> yield of apple and orange crop

inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
],dtype='float32')


In [91]:
target = np.array([
    [56,70],
    [81,101],
    [119,113],
    [22,37],
    [103,119]
],dtype=np.float32)

In [92]:
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

In [93]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)

In [94]:
print(w,b)

tensor([[-1.8135,  1.2783,  0.3731],
        [ 0.3546, -0.1219,  1.8978]], requires_grad=True) tensor([0.0118, 0.9895], requires_grad=True)


In [95]:
def model(x):
  return x @ w.t() + b

In [96]:
preds = model(inputs)
print(preds)

tensor([[ -30.6879,  100.3114],
        [ -28.6521,  143.9871],
        [  35.1640,  125.5732],
        [-116.1983,  102.1353],
        [  23.7110,  146.5965]], grad_fn=<AddBackward0>)


In [97]:
#loss function mse
def mse(actual,target):
  diff = actual - target

  return torch.sum(diff*diff)/diff.numel()


In [98]:
#Error = loss = MSE
loss = mse(preds,target)
print(loss)

tensor(5988.1289, grad_fn=<DivBackward0>)


In [99]:
loss.backward()

In [100]:
print(w)
print(w.grad)

tensor([[-1.8135,  1.2783,  0.3731],
        [ 0.3546, -0.1219,  1.8978]], requires_grad=True)
tensor([[-8633.4902, -8049.1519, -5254.2729],
        [ 3153.2795,  2589.7261,  1825.1160]])


In [101]:
print(b)
print(b.grad)

tensor([0.0118, 0.9895], requires_grad=True)
tensor([-99.5326,  35.7207])


In [102]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [103]:
#adjust parameters
preds = model(inputs)
print(preds)
loss = mse(target,preds)
print(loss)

tensor([[ -30.6879,  100.3114],
        [ -28.6521,  143.9871],
        [  35.1640,  125.5732],
        [-116.1983,  102.1353],
        [  23.7110,  146.5965]], grad_fn=<AddBackward0>)
tensor(5988.1289, grad_fn=<DivBackward0>)


In [104]:
loss.backward()

print(w.grad)
print(b.grad)

tensor([[-8633.4902, -8049.1519, -5254.2729],
        [ 3153.2795,  2589.7261,  1825.1160]])
tensor([-99.5326,  35.7207])


In [105]:
learning_rate = 1e-5
with torch.no_grad():
  w-=w.grad * learning_rate
  b-=b.grad * learning_rate

  w.grad.zero_()
  b.grad.zero_()

In [106]:
preds = model(inputs)
loss = mse(target,preds)
print(loss)

tensor(4285.3994, grad_fn=<DivBackward0>)


In [107]:
for i in range(400):
  preds = model(inputs)
  loss = mse(target,preds)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * learning_rate
    b-=b.grad * learning_rate

    w.grad.zero_()
    b.grad.zero_()
  print(f'epoch {i} loss {loss}')

epoch 0 loss 4285.3994140625
epoch 1 loss 3134.844482421875
epoch 2 loss 2356.428955078125
epoch 3 loss 1828.832275390625
epoch 4 loss 1470.2969970703125
epoch 5 loss 1225.7271728515625
epoch 6 loss 1057.9949951171875
epoch 7 loss 942.0789184570312
epoch 8 loss 861.1171875
epoch 9 loss 803.7468872070312
epoch 10 loss 762.3097534179688
epoch 11 loss 731.6447143554688
epoch 12 loss 708.2734985351562
epoch 13 loss 689.8514404296875
epoch 14 loss 674.7984619140625
epoch 15 loss 662.0487060546875
epoch 16 loss 650.8843994140625
epoch 17 loss 640.8206787109375
epoch 18 loss 631.5304565429688
epoch 19 loss 622.793212890625
epoch 20 loss 614.4598999023438
epoch 21 loss 606.4297485351562
epoch 22 loss 598.6337890625
epoch 23 loss 591.0259399414062
epoch 24 loss 583.5748291015625
epoch 25 loss 576.2584228515625
epoch 26 loss 569.0614624023438
epoch 27 loss 561.9738159179688
epoch 28 loss 554.9878540039062
epoch 29 loss 548.0985107421875
epoch 30 loss 541.3013916015625
epoch 31 loss 534.593872070

In [108]:
preds = model(inputs)
loss = mse(target,preds)
print(loss)

tensor(11.7587, grad_fn=<DivBackward0>)


In [109]:
from math import sqrt
sqrt(loss)

3.4290958667613745

In [110]:
preds

tensor([[ 56.4285,  67.5333],
        [ 80.9564, 103.1001],
        [122.7215, 107.1478],
        [ 16.7013,  40.0053],
        [102.3057, 123.6064]], grad_fn=<AddBackward0>)

In [111]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])