In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

data = load_iris()

X = data.data
y = data.target
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2 , random_state=1)
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

print(f'{pca.components_}\n')
print("explained variance ratio\n")
print(pca.explained_variance_ratio_)

[[ 0.52828393 -0.25412962  0.58193019  0.56364126]
 [ 0.33212851  0.93919659  0.02900891  0.0822125 ]
 [ 0.73274266 -0.19922124 -0.13583859 -0.63635443]]

explained variance ratio

[0.72703821 0.2283104  0.04019711]
